### ISSUE TITLE
Adding new words

### ISSUE THREAD

**Issue by subins2000** [knadh/datuk#1]
A small doc on how to add a new word would be helpful. I see there are two files : https://github.com/knadh/datuk/tree/master/corpus

**Comment by knadh** [comment]
Yep, you're right. Right now, it's a weird mix of TSV + YAML (and it's neither). Will convert this to a standard format and document.

**Comment by subins2000** [comment]
@knadh Any way in which I can help ?

**Comment by knadh** [comment]
@subins2000 I've half done it. Will upload this evening.

**Comment by knadh** [comment]
Pushed https://github.com/knadh/datuk/commit/80fa8c41c9c5f944f0e3edbebfac0397a03371ca.

Updated README as well.
